services: 
  api:
    container_name: "api-service"
    ports: 
      - "8000:8000"
    build: 
      dockerfile: Api/Dockerfile
    volumes: 
      - type: bind
        source: Api/app/generatedCode
        target: /app/app/generatedCode
  business: 
    container_name: "business-service"
    build:
      dockerfile: Business/Dockerfile